# Xiaomi alioth mkinitcpio conf

MODULES+=(
binfmt_misc
snd_soc_sm8250
snd_soc_qcom_common
snd_soc_qcom_sdw
btqca
hci_uart
bluetooth
ath11k_pci
ath11k
snd_soc_cs35l41
snd_soc_cs35l41_i2c
)

HOOKS+=(aliothfw)

COMPRESSION="gzip"
