# Xiaomi alioth mkinitcpio conf

MODULES+=(
snd_soc_sm8250
snd_soc_qcom_common
snd_soc_qcom_sdw
btqca
hci_uart
bluetooth
ath11k_pci
ath11k
cs35l41
cs35l41_i2c
)

HOOKS+=(aliothfw)

COMPRESSION="gzip"
